# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Important note to UOFW Contributors!! 
# Make sure your config variables in your fork matches the variables of the gh-pages branch of the UOFW.

title: UO Framework
description: Documentation for the United Operation Framework
baseurl: /UnitedOperationsFramework # the subpath of your site, e.g. /blog
url: https://unitedoperations.github.io # the base hostname & protocol for your site, e.g. http://example.com
repository: https://github.com/unitedoperations/UnitedOperationsFramework
branch: gh-pages

#permalink: pretty
permalink: /:title/
show_dir_listing: false
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

include:
    - "resources"
    - "docs"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Forum":
    - "//unitedoperations.net"
  "Slack":
      -"//uoframework.slack.com"
  "Github":
    - "//github.com/unitedoperations/UnitedOperationsFramework/"
  "Latest Release":
    - "//github.com/unitedoperations/UnitedOperationsFramework/releases/latest"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: dark

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking:

#theme: "just-the-docs"

markdown: kramdown
kramdown:
    parse_block_html: true

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  
relative_links:
    enabled: true
    collections: false

defaults:
    -   scope:
            path: "docs"
            type: "default"
        values:
            layout: default
            use_title: true
            title: "Default"
            alt_title: "Default Title"
            permalink: /:title/
            redirect_from: 
                - /:title
            # grand_parent: 